[package]
name = "known"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "known"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
notify = "6.1"

[dev-dependencies]
tempfile = "3.8"
